name: valtest9-jo-l3gfu4-1l1yg3
annotations:
  category: CMS
  images: |
    - name: apache-exporter
      image: docker.io/bitnami/apache-exporter:1.0.7-debian-12-r3
    - name: joomla
      image: docker.io/bitnami/joomla:5.1.0-debian-12-r0
  licenses: Apache-2.0
apiVersion: v2
appVersion: 5.1.0
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 18.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Joomla! is an award winning open source CMS platform for building websites
  and applications. It includes page caching, page compression and Let's Encrypt auto-configuration
  support.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/joomla/img/joomla-stack-220x234.png
keywords:
- joomla
- cms
- blog
- http
- php
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/joomla
version: 19.0.2
